var itemsData = [
   { id: 1, name: "Metal Plate", material: "Metal", image: "images/Metal Plate.jpg", details: "" },
   { id: 2, name: "Glass Plate", material: "Glass", image: "images/Glass Plate.jpg", details: "" },
   { id: 3, name: "Ceramic Plate", material: "Ceramic", image: "images/Ceramic Plate.jpg", details: "" },
   { id: 4, name: "Wooden Plate", material: "Wood", image: "", details: "" },
   { id: 5, name: "Plastic Plate", material: "Plastic", image: "", details: "" },
   { id: 6, name: "Metal Bowl", material: "Metal", image: "", details: "" },
   { id: 7, name: "Glass Bowl", material: "Glass", image: "", details: "" },
   { id: 8, name: "Ceramic Bowl", material: "Ceramic", image: "", details: "" },
   { id: 9, name: "Wooden Bowl", material: "Wood", image: "", details: "" },
   { id: 10, name: "Plastic Bowl", material: "Plastic", image: "", details: "" },
   { id: 11, name: "Metal Cup", material: "Metal", image: "", details: "" },
   { id: 12, name: "Glass Cup", material: "Glass", image: "", details: "" },
   { id: 13, name: "Ceramic Cup", material: "Ceramic", image: "", details: "" },
   { id: 14, name: "Wooden Cup", material: "Wood", image: "", details: "" },
   { id: 15, name: "Plastic Cup", material: "Plastic", image: "", details: "" },
   { id: 16, name: "Metal Mug", material: "Metal", image: "", details: "" },
   { id: 17, name: "Glass Mug", material: "Glass", image: "", details: "" },
   { id: 18, name: "Ceramic Mug", material: "Ceramic", image: "", details: "" },
   { id: 19, name: "Wooden Mug", material: "Wood", image: "", details: "" },
   { id: 20, name: "Plastic Mug", material: "Plastic", image: "", details: "" },
   { id: 21, name: "Crystal Drinking Glass", material: "Glass", image: "", details: "" },
   { id: 22, name: "Metal Drinking Glass", material: "Metal", image: "", details: "" },
   { id: 23, name: "Plastic Drinking Glass", material: "Plastic", image: "", details: "" },
   { id: 24, name: "Metal Teacup", material: "Metal", image: "", details: "" },
   { id: 25, name: "Glass Teacup", material: "Glass", image: "", details: "" },
   { id: 26, name: "Ceramic Teacup", material: "Ceramic", image: "", details: "" },
   { id: 27, name: "Wooden Teacup", material: "Wood", image: "", details: "" },
   { id: 28, name: "Plastic Teacup", material: "Plastic", image: "", details: "" },
   { id: 29, name: "Metal Saucer", material: "Metal", image: "", details: "" },
   { id: 30, name: "Glass Saucer", material: "Glass", image: "", details: "" },
   { id: 31, name: "Ceramic Saucer", material: "Ceramic", image: "", details: "" },
   { id: 32, name: "Wooden Saucer", material: "Wood", image: "", details: "" },
   { id: 33, name: "Plastic Saucer", material: "Plastic", image: "", details: "" },
   { id: 34, name: "Metal Teapot", material: "Metal", image: "", details: "" },
   { id: 35, name: "Glass Teapot", material: "Glass", image: "", details: "" },
   { id: 36, name: "Ceramic Teapot", material: "Ceramic", image: "", details: "" },
   { id: 37, name: "Wooden Teapot", material: "Wood", image: "", details: "" },
   { id: 38, name: "Plastic Teapot", material: "Plastic", image: "", details: "" },
   { id: 39, name: "Coffee Maker", material: "Metal", image: "", details: "" },
   { id: 40, name: "Metal Coffee Pot", material: "Metal", image: "", details: "" },
   { id: 41, name: "Glass Coffee Pot", material: "Glass", image: "", details: "" },
   { id: 42, name: "Ceramic Coffee Pot", material: "Ceramic", image: "", details: "" },
   { id: 43, name: "Wooden Coffee Pot", material: "Wood", image: "", details: "" },
   { id: 44, name: "Plastic Coffee Pot", material: "Plastic", image: "", details: "" },
   { id: 45, name: "Metal Kettle", material: "Metal", image: "", details: "" },
   { id: 46, name: "Glass Kettle", material: "Glass", image: "", details: "" },
   { id: 47, name: "Ceramic Kettle", material: "Ceramic", image: "", details: "" },
   { id: 48, name: "Wooden Kettle", material: "Wood", image: "", details: "" },
   { id: 49, name: "Plastic Kettle", material: "Plastic", image: "", details: "" },
   { id: 50, name: "Metal Fork", material: "Metal", image: "", details: "" },
   { id: 51, name: "Glass Fork", material: "Glass", image: "", details: "" },
   { id: 52, name: "Ceramic Fork", material: "Ceramic", image: "", details: "" },
   { id: 53, name: "Wooden Fork", material: "Wood", image: "", details: "" },
   { id: 54, name: "Plastic Fork", material: "Plastic", image: "", details: "" },
   { id: 55, name: "Metal Knife", material: "Metal", image: "", details: "" },
   { id: 56, name: "Ceramic Knife", material: "Ceramic", image: "", details: "" },
   { id: 57, name: "Wooden Knife", material: "Wood", image: "", details: "" },
   { id: 58, name: "Plastic Knife", material: "Plastic", image: "", details: "" },
   { id: 59, name: "Metal Spoon", material: "Metal", image: "", details: "" },
   { id: 60, name: "Glass Spoon", material: "Glass", image: "", details: "" },
   { id: 61, name: "Ceramic Spoon", material: "Ceramic", image: "", details: "" },
   { id: 62, name: "Wooden Spoon", material: "Wood", image: "", details: "" },
   { id: 63, name: "Plastic Spoon", material: "Plastic", image: "", details: "" },
   { id: 64, name: "Metal Ladle", material: "Metal", image: "", details: "" },
   { id: 65, name: "Glass Ladle", material: "Glass", image: "", details: "" },
   { id: 66, name: "Ceramic Ladle", material: "Ceramic", image: "", details: "" },
   { id: 67, name: "Wooden Ladle", material: "Wood", image: "", details: "" },
   { id: 68, name: "Plastic Ladle", material: "Plastic", image: "", details: "" },
   { id: 69, name: "Metal Tongs", material: "Metal", image: "", details: "" },
   { id: 70, name: "Glass Tongs", material: "Glass", image: "", details: "" },
   { id: 71, name: "Ceramic Tongs", material: "Ceramic", image: "", details: "" },
   { id: 72, name: "Wooden Tongs", material: "Wood", image: "", details: "" },
   { id: 73, name: "Plastic Tongs", material: "Plastic", image: "", details: "" },
   { id: 74, name: "Metal Spatula", material: "Metal", image: "", details: "" },
   { id: 75, name: "Glass Spatula", material: "Glass", image: "", details: "" },
   { id: 76, name: "Ceramic Spatula", material: "Ceramic", image: "", details: "" },
   { id: 77, name: "Wooden Spatula", material: "Wood", image: "", details: "" },
   { id: 78, name: "Plastic Spatula", material: "Plastic", image: "", details: "" },
   { id: 79, name: "Cast Iron Skillet", material: "Metal", image: "", details: "" },
   { id: 80, name: "Stainless Steel Skillet", material: "Metal", image: "", details: "" },
   { id: 81, name: "Ceramic Skillet", material: "Ceramic", image: "", details: "" },
   { id: 82, name: "Aluminum Skillet", material: "Metal", image: "", details: "" },
   { id: 83, name: "Cast Iron Frying Pan", material: "Metal", image: "", details: "" },
   { id: 84, name: "Stainless Steel Frying Pan", material: "Metal", image: "", details: "" },
   { id: 85, name: "Ceramic Frying Pan", material: "Ceramic", image: "", details: "" },
   { id: 86, name: "Aluminum Frying Pan", material: "Metal", image: "", details: "" },
   { id: 87, name: "Stainless Steel Saucepan", material: "Metal", image: "", details: "" },
   { id: 88, name: "Ceramic Saucepan", material: "Ceramic", image: "", details: "" },
   { id: 89, name: "Aluminum Saucepan", material: "Metal", image: "", details: "" },
   { id: 90, name: "Copper Saucepan", material: "Metal", image: "", details: "" },
   { id: 91, name: "Stainless Steel Stockpot", material: "Metal", image: "", details: "" },
   { id: 92, name: "Aluminum Stockpot", material: "Metal", image: "", details: "" },
   { id: 93, name: "Copper Stockpot", material: "Metal", image: "", details: "" },
   { id: 94, name: "Cast Iron Dutch Oven", material: "Metal", image: "", details: "" },
   { id: 95, name: "Enameled Cast Iron Dutch Oven", material: "Metal", image: "", details: "" },
   { id: 96, name: "Ceramic Dutch Oven", material: "Ceramic", image: "", details: "" },
   { id: 97, name: "Metal Roasting Pan (Stainless Steel)", material: "Metal", image: "", details: "" },
   { id: 98, name: "Aluminum Roasting Pan", material: "Metal", image: "", details: "" },
   { id: 99, name: "Nonstick Roasting Pan", material: "Metal", image: "", details: "" },
   { id: 100, name: "Metal Baking Sheet (Aluminum)", material: "Metal", image: "", details: "" },
   { id: 101, name: "Nonstick Baking Sheet", material: "Metal", image: "", details: "" },
   { id: 102, name: "Silicone Baking Sheet", material: "Plastic", image: "", details: "" },
   { id: 103, name: "Metal Oven Tray", material: "Metal", image: "", details: "" },
   { id: 104, name: "Nonstick Oven Tray", material: "Metal", image: "", details: "" },
   { id: 105, name: "Silicone Oven Tray", material: "Plastic", image: "", details: "" },
   { id: 106, name: "Ceramic Casserole Dish", material: "Ceramic", image: "", details: "" },
   { id: 107, name: "Glass Casserole Dish", material: "Glass", image: "", details: "" },
   { id: 108, name: "Metal Casserole Dish", material: "Metal", image: "", details: "" },
   { id: 109, name: "Stoneware Casserole Dish", material: "Ceramic", image: "", details: "" },
   { id: 110, name: "Metal Pie Pan", material: "Metal", image: "", details: "" },
   { id: 111, name: "Glass Pie Pan", material: "Glass", image: "", details: "" },
   { id: 112, name: "Ceramic Pie Pan", material: "Ceramic", image: "", details: "" },
   { id: 113, name: "Aluminum Pie Pan", material: "Metal", image: "", details: "" },
   { id: 114, name: "Metal Tart Pan", material: "Metal", image: "", details: "" },
   { id: 115, name: "Nonstick Tart Pan", material: "Metal", image: "", details: "" },
   { id: 116, name: "Ceramic Tart Pan", material: "Ceramic", image: "", details: "" },
   { id: 117, name: "Metal Muffin Tin", material: "Metal", image: "", details: "" },
   { id: 118, name: "Silicone Muffin Tin", material: "Plastic", image: "", details: "" },
   { id: 119, name: "Nonstick Muffin Tin", material: "Metal", image: "", details: "" },
   { id: 120, name: "Metal Loaf Pan", material: "Metal", image: "", details: "" },
   { id: 121, name: "Glass Loaf Pan", material: "Glass", image: "", details: "" },
   { id: 122, name: "Ceramic Loaf Pan", material: "Ceramic", image: "", details: "" },
   { id: 123, name: "Nonstick Loaf Pan", material: "Metal", image: "", details: "" },
   { id: 124, name: "Metal Cookie Sheet (Aluminum)", material: "Metal", image: "", details: "" },
   { id: 125, name: "Nonstick Cookie Sheet", material: "Metal", image: "", details: "" },
   { id: 126, name: "Silicone Cookie Sheet", material: "Plastic", image: "", details: "" },
   { id: 127, name: "Stainless Steel Cooling Rack", material: "Metal", image: "", details: "" },
   { id: 128, name: "Plastic Cooling Rack", material: "Plastic", image: "", details: "" },
   { id: 129, name: "Cast Iron Griddle", material: "Metal", image: "", details: "" },
   { id: 130, name: "Nonstick Griddle", material: "Metal", image: "", details: "" },
   { id: 131, name: "Aluminum Griddle", material: "Metal", image: "", details: "" },
   { id: 132, name: "Stainless Steel Pressure Cooker", material: "Metal", image: "", details: "" },
   { id: 133, name: "Aluminum Pressure Cooker", material: "Metal", image: "", details: "" },
   { id: 134, name: "Slow Cooker", material: "Metal", image: "", details: "" },
   { id: 135, name: "Rice Cooker", material: "Metal", image: "", details: "" },
   { id: 136, name: "Carbon Steel Wok", material: "Metal", image: "", details: "" },
   { id: 137, name: "Cast Iron Wok", material: "Metal", image: "", details: "" },
   { id: 138, name: "Nonstick Wok", material: "Metal", image: "", details: "" },
   { id: 139, name: "Stainless Steel Wok", material: "Metal", image: "", details: "" },
   { id: 140, name: "Stainless Steel Steamer Basket", material: "Metal", image: "", details: "" },
   { id: 141, name: "Bamboo Steamer Basket", material: "Wood", image: "", details: "" },
   { id: 142, name: "Silicone Steamer Basket", material: "Plastic", image: "", details: "" },
   { id: 143, name: "Metal Colander", material: "Metal", image: "", details: "" },
   { id: 144, name: "Plastic Colander", material: "Plastic", image: "", details: "" },
   { id: 145, name: "Silicone Colander", material: "Plastic", image: "", details: "" },
   { id: 146, name: "Ceramic Colander", material: "Ceramic", image: "", details: "" },
   { id: 147, name: "Bamboo Colander", material: "Wood", image: "", details: "" },
   { id: 148, name: "Metal Strainer (Fine Mesh)", material: "Metal", image: "", details: "" },
   { id: 149, name: "Plastic Strainer", material: "Plastic", image: "", details: "" },
   { id: 150, name: "Silicone Strainer", material: "Plastic", image: "", details: "" },
   { id: 151, name: "Ceramic Strainer", material: "Ceramic", image: "", details: "" },
   { id: 152, name: "Metal Sieve", material: "Metal", image: "", details: "" },
   { id: 153, name: "Plastic Sieve", material: "Plastic", image: "", details: "" },
   { id: 154, name: "Silicone Sieve", material: "Plastic", image: "", details: "" },
   { id: 155, name: "Wooden Sieve", material: "Wood", image: "", details: "" },
   { id: 156, name: "Metal Mixing Bowl", material: "Metal", image: "", details: "" },
   { id: 157, name: "Glass Mixing Bowl", material: "Glass", image: "", details: "" },
   { id: 158, name: "Ceramic Mixing Bowl", material: "Ceramic", image: "", details: "" },
   { id: 159, name: "Plastic Mixing Bowl", material: "Plastic", image: "", details: "" },
   { id: 160, name: "Wooden Mixing Bowl", material: "Wood", image: "", details: "" },
   { id: 161, name: "Metal Measuring Cup", material: "Metal", image: "", details: "" },
   { id: 162, name: "Glass Measuring Cup", material: "Glass", image: "", details: "" },
   { id: 163, name: "Plastic Measuring Cup", material: "Plastic", image: "", details: "" },
   { id: 164, name: "Ceramic Measuring Cup", material: "Ceramic", image: "", details: "" },
   { id: 165, name: "Stainless Steel Measuring Cup", material: "Metal", image: "", details: "" },
   { id: 166, name: "Metal Measuring Spoon", material: "Metal", image: "", details: "" },
   { id: 167, name: "Plastic Measuring Spoon", material: "Plastic", image: "", details: "" },
   { id: 168, name: "Silicone Measuring Spoon", material: "Plastic", image: "", details: "" },
   { id: 169, name: "Stainless Steel Measuring Spoon", material: "Metal", image: "", details: "" },
   { id: 170, name: "Blender", material: "Metal", image: "", details: "" },
   { id: 171, name: "Food Processor", material: "Metal", image: "", details: "" },
   { id: 172, name: "Juicer", material: "Metal", image: "", details: "" },
   { id: 173, name: "Stone Mortar and Pestle", material: "Ceramic", image: "", details: "" },
   { id: 174, name: "Ceramic Mortar and Pestle", material: "Ceramic", image: "", details: "" },
   { id: 175, name: "Granite Mortar and Pestle", material: "Ceramic", image: "", details: "" },
   { id: 176, name: "Wooden Mortar and Pestle", material: "Wood", image: "", details: "" },
   { id: 177, name: "Metal Mortar and Pestle", material: "Metal", image: "", details: "" },
   { id: 178, name: "Wood Cutting Board", material: "Wood", image: "", details: "" },
   { id: 179, name: "Plastic Cutting Board", material: "Plastic", image: "", details: "" },
   { id: 180, name: "Bamboo Cutting Board", material: "Wood", image: "", details: "" },
   { id: 181, name: "Glass Cutting Board", material: "Glass", image: "", details: "" },
   { id: 182, name: "Marble Cutting Board", material: "Ceramic", image: "", details: "" },
   { id: 183, name: "Composite Cutting Board", material: "Plastic", image: "", details: "" },
   { id: 184, name: "Wood Knife Block", material: "Wood", image: "", details: "" },
   { id: 185, name: "Plastic Knife Block", material: "Plastic", image: "", details: "" },
   { id: 186, name: "Metal Knife Block", material: "Metal", image: "", details: "" },
   { id: 187, name: "Metal Can Opener", material: "Metal", image: "", details: "" },
   { id: 188, name: "Plastic Can Opener", material: "Plastic", image: "", details: "" },
   { id: 189, name: "Metal Bottle Opener", material: "Metal", image: "", details: "" },
   { id: 190, name: "Wooden Bottle Opener", material: "Wood", image: "", details: "" },
   { id: 191, name: "Plastic Bottle Opener", material: "Plastic", image: "", details: "" },
   { id: 192, name: "Metal Corkscrew", material: "Metal", image: "", details: "" },
   { id: 193, name: "Wooden Corkscrew", material: "Wood", image: "", details: "" },
   { id: 194, name: "Plastic Corkscrew", material: "Plastic", image: "", details: "" },
   { id: 195, name: "Plastic Ice Cube Tray", material: "Plastic", image: "", details: "" },
   { id: 196, name: "Silicone Ice Cube Tray", material: "Plastic", image: "", details: "" },
   { id: 197, name: "Metal Ice Cube Tray", material: "Metal", image: "", details: "" },
   { id: 198, name: "Glass Ice Cube Tray", material: "Glass", image: "", details: "" },
   { id: 199, name: "Metal Pie Dish", material: "Metal", image: "", details: "" },
   { id: 200, name: "Glass Pie Dish", material: "Glass", image: "", details: "" },
   { id: 201, name: "Ceramic Pie Dish", material: "Ceramic", image: "", details: "" },
   { id: 202, name: "Plastic Pie Dish", material: "Plastic", image: "", details: "" },
   { id: 203, name: "Silicone Pastry Brush", material: "Plastic", image: "", details: "" },
   { id: 204, name: "Natural Bristle Pastry Brush", material: "Wood", image: "", details: "" },
   { id: 205, name: "Wood Rolling Pin", material: "Wood", image: "", details: "" },
   { id: 206, name: "Marble Rolling Pin", material: "Ceramic", image: "", details: "" },
   { id: 207, name: "Stainless Steel Rolling Pin", material: "Metal", image: "", details: "" },
   { id: 208, name: "Glass Rolling Pin", material: "Glass", image: "", details: "" },
   { id: 209, name: "Metal Pastry Cutter", material: "Metal", image: "", details: "" },
   { id: 210, name: "Plastic Pastry Cutter", material: "Plastic", image: "", details: "" },
   { id: 211, name: "Stainless Steel Pastry Cutter", material: "Metal", image: "", details: "" },
   { id: 212, name: "Metal Grater", material: "Metal", image: "", details: "" },
   { id: 213, name: "Plastic Grater", material: "Plastic", image: "", details: "" },
   { id: 214, name: "Ceramic Grater", material: "Ceramic", image: "", details: "" },
   { id: 215, name: "Metal Zester", material: "Metal", image: "", details: "" },
   { id: 216, name: "Plastic Zester", material: "Plastic", image: "", details: "" },
   { id: 217, name: "Metal Mandoline Slicer", material: "Metal", image: "", details: "" },
   { id: 218, name: "Plastic Mandoline Slicer", material: "Plastic", image: "", details: "" },
   { id: 219, name: "Metal Food Chopper", material: "Metal", image: "", details: "" },
   { id: 220, name: "Plastic Food Chopper", material: "Plastic", image: "", details: "" },
   { id: 221, name: "Metal Food Mill", material: "Metal", image: "", details: "" },
   { id: 222, name: "Plastic Food Mill", material: "Plastic", image: "", details: "" },
   { id: 223, name: "Plastic Salad Spinner", material: "Plastic", image: "", details: "" },
   { id: 224, name: "Metal Salad Spinner", material: "Metal", image: "", details: "" },
   { id: 225, name: "Metal Vegetable Peeler", material: "Metal", image: "", details: "" },
   { id: 226, name: "Plastic Vegetable Peeler", material: "Plastic", image: "", details: "" },
   { id: 227, name: "Metal Manual Egg Beater", material: "Metal", image: "", details: "" },
   { id: 228, name: "Plastic Manual Egg Beater", material: "Plastic", image: "", details: "" },
   { id: 229, name: "Metal Whisk", material: "Metal", image: "", details: "" },
   { id: 230, name: "Silicone Whisk", material: "Plastic", image: "", details: "" },
   { id: 231, name: "Wooden Whisk", material: "Wood", image: "", details: "" },
   { id: 232, name: "Metal Mixing Spatula", material: "Metal", image: "", details: "" },
   { id: 233, name: "Plastic Mixing Spatula", material: "Plastic", image: "", details: "" },
   { id: 234, name: "Silicone Mixing Spatula", material: "Plastic", image: "", details: "" },
   { id: 235, name: "Wooden Mixing Spatula", material: "Wood", image: "", details: "" },
   { id: 236, name: "Metal Soup Ladle", material: "Metal", image: "", details: "" },
   { id: 237, name: "Plastic Soup Ladle", material: "Plastic", image: "", details: "" },
   { id: 238, name: "Wooden Soup Ladle", material: "Wood", image: "", details: "" },
   { id: 239, name: "Ceramic Soup Ladle", material: "Ceramic", image: "", details: "" },
   { id: 240, name: "Glass Cream Pitcher", material: "Glass", image: "", details: "" },
   { id: 241, name: "Ceramic Cream Pitcher", material: "Ceramic", image: "", details: "" },
   { id: 242, name: "Plastic Cream Pitcher", material: "Plastic", image: "", details: "" },
   { id: 243, name: "Metal Cream Pitcher", material: "Metal", image: "", details: "" },
   { id: 244, name: "Glass Butter Dish", material: "Glass", image: "", details: "" },
   { id: 245, name: "Ceramic Butter Dish", material: "Ceramic", image: "", details: "" },
   { id: 246, name: "Plastic Butter Dish", material: "Plastic", image: "", details: "" },
   { id: 247, name: "Metal Butter Dish", material: "Metal", image: "", details: "" },
   { id: 248, name: "Metal Cheese Grater", material: "Metal", image: "", details: "" },
   { id: 249, name: "Plastic Cheese Grater", material: "Plastic", image: "", details: "" },
   { id: 250, name: "Ceramic Fondue Pot", material: "Ceramic", image: "", details: "" },
   { id: 251, name: "Metal Fondue Pot", material: "Metal", image: "", details: "" },
   { id: 252, name: "Cast Iron Fondue Pot", material: "Metal", image: "", details: "" },
   { id: 253, name: "Metal Fondue Fork", material: "Metal", image: "", details: "" },
   { id: 254, name: "Wooden Fondue Fork", material: "Wood", image: "", details: "" },
   { id: 255, name: "Bamboo Sushi Rolling Mat", material: "Wood", image: "", details: "" },
   { id: 256, name: "Plastic Sushi Rolling Mat", material: "Plastic", image: "", details: "" },
   { id: 257, name: "Plastic Bento Box", material: "Plastic", image: "", details: "" },
   { id: 258, name: "Metal Bento Box", material: "Metal", image: "", details: "" },
   { id: 259, name: "Wooden Bento Box", material: "Wood", image: "", details: "" },
   { id: 260, name: "Ceramic Bento Box", material: "Ceramic", image: "", details: "" },
   { id: 261, name: "Plastic Tupperware Container", material: "Plastic", image: "", details: "" },
   { id: 262, name: "Glass Food Storage Container", material: "Glass", image: "", details: "" },
   { id: 263, name: "Stainless Steel Food Storage Container", material: "Metal", image: "", details: "" },
   { id: 264, name: "Glass Salad Bowl", material: "Glass", image: "", details: "" },
   { id: 265, name: "Ceramic Salad Bowl", material: "Ceramic", image: "", details: "" },
   { id: 266, name: "Metal Salad Bowl", material: "Metal", image: "", details: "" },
   { id: 267, name: "Wooden Salad Bowl", material: "Wood", image: "", details: "" },
   { id: 268, name: "Plastic Salad Bowl", material: "Plastic", image: "", details: "" },
   { id: 269, name: "Metal Serving Tray", material: "Metal", image: "", details: "" },
   { id: 270, name: "Wooden Serving Tray", material: "Wood", image: "", details: "" },
   { id: 271, name: "Plastic Serving Tray", material: "Plastic", image: "", details: "" },
   { id: 272, name: "Glass Serving Tray", material: "Glass", image: "", details: "" },
   { id: 273, name: "Ceramic Serving Tray", material: "Ceramic", image: "", details: "" },
   { id: 274, name: "Metal Serving Spoon", material: "Metal", image: "", details: "" },
   { id: 275, name: "Wooden Serving Spoon", material: "Wood", image: "", details: "" },
   { id: 276, name: "Plastic Serving Spoon", material: "Plastic", image: "", details: "" },
   { id: 277, name: "Ceramic Serving Spoon", material: "Ceramic", image: "", details: "" },
   { id: 278, name: "Metal Serving Fork", material: "Metal", image: "", details: "" },
   { id: 279, name: "Wooden Serving Fork", material: "Wood", image: "", details: "" },
   { id: 280, name: "Plastic Serving Fork", material: "Plastic", image: "", details: "" },
   { id: 281, name: "Ceramic Serving Fork", material: "Ceramic", image: "", details: "" },
   { id: 282, name: "Ceramic Soup Bowl", material: "Ceramic", image: "", details: "" },
   { id: 283, name: "Glass Soup Bowl", material: "Glass", image: "", details: "" },
   { id: 284, name: "Metal Soup Bowl", material: "Metal", image: "", details: "" },
   { id: 285, name: "Wooden Soup Bowl", material: "Wood", image: "", details: "" },
   { id: 286, name: "Plastic Soup Bowl", material: "Plastic", image: "", details: "" },
   { id: 287, name: "Ceramic Dessert Plate", material: "Ceramic", image: "", details: "" },
   { id: 288, name: "Glass Dessert Plate", material: "Glass", image: "", details: "" },
   { id: 289, name: "Metal Dessert Plate", material: "Metal", image: "", details: "" },
   { id: 290, name: "Plastic Dessert Plate", material: "Plastic", image: "", details: "" },
   { id: 291, name: "Wooden Dessert Plate", material: "Wood", image: "", details: "" },
   { id: 292, name: "Ceramic Snack Bowl", material: "Ceramic", image: "", details: "" },
   { id: 293, name: "Glass Snack Bowl", material: "Glass", image: "", details: "" },
   { id: 294, name: "Metal Snack Bowl", material: "Metal", image: "", details: "" },
   { id: 295, name: "Plastic Snack Bowl", material: "Plastic", image: "", details: "" },
   { id: 296, name: "Wooden Snack Bowl", material: "Wood", image: "", details: "" },
   { id: 297, name: "Metal Water Bottle (Stainless Steel)", material: "Metal", image: "", details: "" },
   { id: 298, name: "Plastic Water Bottle", material: "Plastic", image: "", details: "" },
   { id: 299, name: "Glass Water Bottle", material: "Glass", image: "", details: "" },
   { id: 300, name: "Aluminum Water Bottle", material: "Metal", image: "", details: "" },
   { id: 301, name: "Stainless Steel Thermos", material: "Metal", image: "", details: "" },
   { id: 302, name: "Plastic Thermos", material: "Plastic", image: "", details: "" },
   { id: 303, name: "Glass Milk Jug", material: "Glass", image: "", details: "" },
   { id: 304, name: "Plastic Milk Jug", material: "Plastic", image: "", details: "" },
   { id: 305, name: "Ceramic Milk Jug", material: "Ceramic", image: "", details: "" },
   { id: 306, name: "Glass Pitcher", material: "Glass", image: "", details: "" },
   { id: 307, name: "Ceramic Pitcher", material: "Ceramic", image: "", details: "" },
   { id: 308, name: "Plastic Pitcher", material: "Plastic", image: "", details: "" },
   { id: 309, name: "Metal Pitcher", material: "Metal", image: "", details: "" },
   { id: 310, name: "Metal Ice Bucket", material: "Metal", image: "", details: "" },
   { id: 311, name: "Plastic Ice Bucket", material: "Plastic", image: "", details: "" },
   { id: 312, name: "Glass Ice Bucket", material: "Glass", image: "", details: "" },
   { id: 313, name: "Glass Beverage Dispenser", material: "Glass", image: "", details: "" },
   { id: 314, name: "Plastic Beverage Dispenser", material: "Plastic", image: "", details: "" },
   { id: 315, name: "Metal Beverage Dispenser", material: "Metal", image: "", details: "" },
   { id: 316, name: "Plastic Food Storage Container", material: "Plastic", image: "", details: "" },
   { id: 317, name: "Glass Food Storage Container", material: "Glass", image: "", details: "" },
   { id: 318, name: "Stainless Steel Food Storage Container", material: "Metal", image: "", details: "" },
   { id: 319, name: "Ceramic Food Storage Container", material: "Ceramic", image: "", details: "" },
   { id: 320, name: "Metal Pizza Cutter", material: "Metal", image: "", details: "" },
   { id: 321, name: "Plastic Pizza Cutter", material: "Plastic", image: "", details: "" },
   { id: 322, name: "Metal Salad Tongs", material: "Metal", image: "", details: "" },
   { id: 323, name: "Plastic Salad Tongs", material: "Plastic", image: "", details: "" },
   { id: 324, name: "Wooden Salad Tongs", material: "Wood", image: "", details: "" },
   { id: 325, name: "Fabric Pot Holder (Cotton)", material: "Fabric", image: "", details: "" },
   { id: 326, name: "Silicone Pot Holder", material: "Plastic", image: "", details: "" },
   { id: 327, name: "Fabric Oven Mitt", material: "Fabric", image: "", details: "" },
   { id: 328, name: "Silicone Oven Mitt", material: "Plastic", image: "", details: "" },
   { id: 329, name: "Metal Spice Grinder", material: "Metal", image: "", details: "" },
   { id: 330, name: "Plastic Spice Grinder", material: "Plastic", image: "", details: "" },
   { id: 331, name: "Ceramic Spice Grinder", material: "Ceramic", image: "", details: "" },
   { id: 332, name: "Metal Herb Stripper", material: "Metal", image: "", details: "" },
   { id: 333, name: "Plastic Herb Stripper", material: "Plastic", image: "", details: "" },
   { id: 334, name: "Metal Egg Separator", material: "Metal", image: "", details: "" },
   { id: 335, name: "Plastic Egg Separator", material: "Plastic", image: "", details: "" },
   { id: 336, name: "Metal Cooking Thermometer", material: "Metal", image: "", details: "" },
   { id: 337, name: "Plastic Cooking Thermometer", material: "Plastic", image: "", details: "" },
   { id: 338, name: "Digital Cooking Thermometer", material: "Metal", image: "", details: "" },
   { id: 339, name: "Stainless Steel Cooking Thermometer", material: "Metal", image: "", details: "" },
   { id: 340, name: "Digital Food Scale", material: "Metal", image: "", details: "" },
   { id: 341, name: "Mechanical Food Scale", material: "Metal", image: "", details: "" },
   { id: 342, name: "Metal Pressure Canner", material: "Metal", image: "", details: "" },
   { id: 343, name: "Aluminum Pressure Canner", material: "Metal", image: "", details: "" },
   { id: 344, name: "Metal Food Steamer", material: "Metal", image: "", details: "" },
   { id: 345, name: "Plastic Food Steamer", material: "Plastic", image: "", details: "" },
   { id: 346, name: "Stainless Steel Food Steamer", material: "Metal", image: "", details: "" },
   { id: 347, name: "Metal Butter Cutter", material: "Metal", image: "", details: "" },
   { id: 348, name: "Plastic Butter Cutter", material: "Plastic", image: "", details: "" },
   { id: 349, name: "Metal Meat Tenderizer", material: "Metal", image: "", details: "" },
   { id: 350, name: "Wooden Meat Tenderizer", material: "Wood", image: "", details: "" },
   { id: 351, name: "Plastic Meat Tenderizer", material: "Plastic", image: "", details: "" },
   { id: 352, name: "Metal Grill Tongs", material: "Metal", image: "", details: "" },
   { id: 353, name: "Wooden Grill Tongs", material: "Wood", image: "", details: "" },
   { id: 354, name: "Plastic Grill Tongs", material: "Plastic", image: "", details: "" },
   { id: 355, name: "Metal Skewer", material: "Metal", image: "", details: "" },
   { id: 356, name: "Bamboo Skewer", material: "Wood", image: "", details: "" },
   { id: 357, name: "Wooden Skewer", material: "Wood", image: "", details: "" },
   { id: 358, name: "Stainless Steel Skewer", material: "Metal", image: "", details: "" },
   { id: 359, name: "Metal Barbecue Fork", material: "Metal", image: "", details: "" },
   { id: 360, name: "Wooden Barbecue Fork", material: "Wood", image: "", details: "" },
   { id: 361, name: "Plastic Barbecue Fork", material: "Plastic", image: "", details: "" },
   { id: 362, name: "Plastic Fondant Smoother", material: "Plastic", image: "", details: "" },
   { id: 363, name: "Metal Fondant Smoother", material: "Metal", image: "", details: "" },
   { id: 364, name: "Metal Crinkle Cutter", material: "Metal", image: "", details: "" },
   { id: 365, name: "Plastic Crinkle Cutter", material: "Plastic", image: "", details: "" },
   { id: 366, name: "Stainless Steel Crinkle Cutter", material: "Metal", image: "", details: "" },
   { id: 367, name: "Plastic Dough Docker", material: "Plastic", image: "", details: "" },
   { id: 368, name: "Metal Dough Docker", material: "Metal", image: "", details: "" },
   { id: 369, name: "Metal Pastry Wheel", material: "Metal", image: "", details: "" },
   { id: 370, name: "Plastic Pastry Wheel", material: "Plastic", image: "", details: "" },
   { id: 371, name: "Metal Egg Poacher", material: "Metal", image: "", details: "" },
   { id: 372, name: "Silicone Egg Poacher", material: "Plastic", image: "", details: "" },
   { id: 373, name: "Ceramic Egg Poacher", material: "Ceramic", image: "", details: "" },
   { id: 374, name: "Metal Splatter Screen", material: "Metal", image: "", details: "" },
   { id: 375, name: "Silicone Splatter Screen", material: "Plastic", image: "", details: "" },
   { id: 376, name: "Plastic Splatter Screen", material: "Plastic", image: "", details: "" },
   { id: 377, name: "Silicone Baking Mat", material: "Plastic", image: "", details: "" },
   { id: 378, name: "Metal Coffee Grinder", material: "Metal", image: "", details: "" },
   { id: 379, name: "Plastic Coffee Grinder", material: "Plastic", image: "", details: "" },
   { id: 380, name: "Metal Popcorn Maker", material: "Metal", image: "", details: "" },
   { id: 381, name: "Plastic Popcorn Maker", material: "Plastic", image: "", details: "" },
   { id: 382, name: "Panini Press", material: "Metal", image: "", details: "" },
   { id: 383, name: "Electric Griddle", material: "Metal", image: "", details: "" },
   { id: 384, name: "Sous Vide Machine", material: "Metal", image: "", details: "" },
   { id: 385, name: "Vacuum Sealer", material: "Metal", image: "", details: "" },
   { id: 386, name: "Metal Salad Dressing Mixer", material: "Metal", image: "", details: "" },
   { id: 387, name: "Plastic Salad Dressing Mixer", material: "Plastic", image: "", details: "" },
   { id: 388, name: "Metal Candy Thermometer", material: "Metal", image: "", details: "" },
   { id: 389, name: "Plastic Candy Thermometer", material: "Plastic", image: "", details: "" },
   { id: 390, name: "Digital Candy Thermometer", material: "Metal", image: "", details: "" },
   { id: 391, name: "Ice Cream Maker", material: "Metal", image: "", details: "" }
 ];
 