var itemsData = [
  { id: 1, name: "Metal Plate", material: "Metal", image: "images/Metal Plate.jpg", details: "" },
  { id: 2, name: "Glass Plate", material: "Glass", image: "images/Glass Plate.jpg", details: "" },
  { id: 3, name: "Ceramic Plate", material: "Ceramic", image: "images/Ceramic Plate.jpg", details: "" },
  { id: 4, name: "Wooden Plate", material: "Wood", image: "images/Wooden Plate.jpg", details: "" },
  { id: 5, name: "Plastic Plate", material: "Plastic", image: "images/Plastic Plate.jpg", details: "" },
  { id: 6, name: "Metal Bowl", material: "Metal", image: "images/Metal Bowl.jpg", details: "" },
  { id: 7, name: "Glass Bowl", material: "Glass", image: "images/Glass Bowl.jpg", details: "" },
  { id: 8, name: "Ceramic Bowl", material: "Ceramic", image: "images/Ceramic Bowl.jpg", details: "" },
  { id: 9, name: "Wooden Bowl", material: "Wood", image: "images/Wooden Bowl.jpg", details: "" },
  { id: 10, name: "Plastic Bowl", material: "Plastic", image: "images/Plastic Bowl.jpg", details: "" },
  { id: 11, name: "Metal Cup", material: "Metal", image: "images/Metal Cup.jpg", details: "" },
  { id: 12, name: "Glass Cup", material: "Glass", image: "images/Glass Cup.jpg", details: "" },
  { id: 13, name: "Ceramic Cup", material: "Ceramic", image: "images/Ceramic Cup.jpg", details: "" },
  { id: 14, name: "Wooden Cup", material: "Wood", image: "images/Wooden Cup.jpg", details: "" },
  { id: 15, name: "Plastic Cup", material: "Plastic", image: "images/Plastic Cup.jpg", details: "" },
  { id: 16, name: "Metal Mug", material: "Metal", image: "images/Metal Mug.jpg", details: "" },
  { id: 17, name: "Glass Mug", material: "Glass", image: "images/Glass Mug.jpg", details: "" },
  { id: 18, name: "Ceramic Mug", material: "Ceramic", image: "images/Ceramic Mug.jpg", details: "" },
  { id: 19, name: "Wooden Mug", material: "Wood", image: "images/Wooden Mug.jpg", details: "" },
  { id: 20, name: "Plastic Mug", material: "Plastic", image: "images/Plastic Mug.jpg", details: "" },
  { id: 24, name: "Metal Teacup", material: "Metal", image: "images/Metal Teacup.jpg", details: "" },
  { id: 25, name: "Glass Teacup", material: "Glass", image: "images/Glass Teacup.jpg", details: "" },
  { id: 26, name: "Ceramic Teacup", material: "Ceramic", image: "images/Ceramic Teacup.jpg", details: "" },
  { id: 27, name: "Wooden Teacup", material: "Wood", image: "images/Wooden Teacup.jpg", details: "" },
  { id: 29, name: "Metal Saucer", material: "Metal", image: "images/Metal Saucer.jpg", details: "" },
  { id: 30, name: "Glass Saucer", material: "Glass", image: "images/Glass Saucer.jpg", details: "" },
  { id: 31, name: "Ceramic Saucer", material: "Ceramic", image: "images/Ceramic Saucer.jpg", details: "" },
  { id: 32, name: "Wooden Saucer", material: "Wood", image: "images/Wooden Saucer.jpg", details: "" },
  { id: 33, name: "Plastic Saucer", material: "Plastic", image: "images/Plastic Saucer.jpg", details: "" },
  { id: 34, name: "Metal Teapot", material: "Metal", image: "images/Metal Teapot.jpg", details: "" },
  { id: 35, name: "Glass Teapot", material: "Glass", image: "images/Glass Teapot.jpg", details: "" },
  { id: 36, name: "Ceramic Teapot", material: "Ceramic", image: "images/Ceramic Teapot.jpg", details: "" },
  { id: 37, name: "Wooden Teapot", material: "Wood", image: "images/Wooden Teapot.jpg", details: "" },
  { id: 39, name: "Coffee Maker", material: "Metal", image: "images/Coffee Maker.jpg", details: "" },
  { id: 40, name: "Metal Coffee Pot", material: "Metal", image: "images/Metal Coffee Pot.jpg", details: "" },
  { id: 41, name: "Glass Coffee Pot", material: "Glass", image: "images/Glass Coffee Pot.jpg", details: "" },
  { id: 42, name: "Ceramic Coffee Pot", material: "Ceramic", image: "images/Ceramic Coffee Pot.jpg", details: "" },
  { id: 45, name: "Metal Kettle", material: "Metal", image: "images/Metal Kettle.jpg", details: "" },
  { id: 46, name: "Glass Kettle", material: "Glass", image: "images/Glass Kettle.jpg", details: "" },
  { id: 47, name: "Ceramic Kettle", material: "Ceramic", image: "images/Ceramic Kettle.jpg", details: "" },
  { id: 48, name: "Wooden Kettle", material: "Wood", image: "images/Wooden Kettle.jpg", details: "" },
  { id: 49, name: "Plastic Kettle", material: "Plastic", image: "images/Plastic Kettle.jpg", details: "" },
  { id: 50, name: "Metal Fork", material: "Metal", image: "images/Metal Fork.jpg", details: "" },
  { id: 51, name: "Glass Fork", material: "Glass", image: "images/Glass Fork.jpg", details: "" },
  { id: 52, name: "Ceramic Fork", material: "Ceramic", image: "images/Ceramic Fork.jpg", details: "" },
  { id: 53, name: "Wooden Fork", material: "Wood", image: "images/Wooden Fork.jpg", details: "" },
  { id: 54, name: "Plastic Fork", material: "Plastic", image: "images/Plastic Fork.jpg", details: "" },
  { id: 55, name: "Metal Knife", material: "Metal", image: "images/Metal Knife.jpg", details: "" },
  { id: 56, name: "Ceramic Knife", material: "Ceramic", image: "images/Ceramic Knife.jpg", details: "" },
  { id: 58, name: "Plastic Knife", material: "Plastic", image: "images/Plastic Knife.jpg", details: "" },
  { id: 59, name: "Metal Spoon", material: "Metal", image: "images/Metal Spoon.jpg", details: "" },
  { id: 60, name: "Glass Spoon", material: "Glass", image: "images/Glass Spoon.jpg", details: "" },
  { id: 61, name: "Ceramic Spoon", material: "Ceramic", image: "images/Ceramic Spoon.jpg", details: "" },
  { id: 62, name: "Wooden Spoon", material: "Wood", image: "images/Wooden Spoon.jpg", details: "" },
  { id: 63, name: "Plastic Spoon", material: "Plastic", image: "images/Plastic Spoon.jpg", details: "" },
  { id: 64, name: "Metal Ladle", material: "Metal", image: "images/Metal Ladle.jpg", details: "" },
  { id: 65, name: "Glass Ladle", material: "Glass", image: "images/Glass Ladle.jpg", details: "" },
  { id: 66, name: "Ceramic Ladle", material: "Ceramic", image: "images/Ceramic Ladle.jpg", details: "" },
  { id: 67, name: "Wooden Ladle", material: "Wood", image: "images/Wooden Ladle.jpg", details: "" },
  { id: 68, name: "Plastic Ladle", material: "Plastic", image: "images/Plastic Ladle.jpg", details: "" },
  { id: 69, name: "Metal Tongs", material: "Metal", image: "images/Metal Tongs.jpg", details: "" },
  { id: 72, name: "Wooden Tongs", material: "Wood", image: "images/Wooden Tongs.jpg", details: "" },
  { id: 73, name: "Plastic Tongs", material: "Plastic", image: "images/Plastic Tongs.jpg", details: "" },
  { id: 74, name: "Metal Spatula", material: "Metal", image: "images/Metal Spatula.jpg", details: "" },
  { id: 77, name: "Wooden Spatula", material: "Wood", image: "images/Wooden Spatula.jpg", details: "" },
  { id: 79, name: "Cast Iron Skillet", material: "Metal", image: "images/Cast Iron Skillet.jpg", details: "" },
  { id: 80, name: "Stainless Steel Skillet", material: "Metal", image: "images/Stainless Steel Skillet.jpg", details: "" },
  { id: 81, name: "Ceramic Skillet", material: "Ceramic", image: "images/Ceramic Skillet.jpg", details: "" },
  { id: 83, name: "Cast Iron Frying Pan", material: "Metal", image: "images/Cast Iron Frying Pan.jpg", details: "" },
  { id: 84, name: "Stainless Steel Frying Pan", material: "Metal", image: "images/Stainless Steel Frying Pan.jpg", details: "" },
  { id: 85, name: "Ceramic Frying Pan", material: "Ceramic", image: "images/Ceramic Frying Pan.jpg", details: "" },
  { id: 86, name: "Aluminum Frying Pan", material: "Metal", image: "images/Aluminum Frying Pan.jpg", details: "" },
  { id: 87, name: "Stainless Steel Saucepan", material: "Metal", image: "images/Stainless Steel Saucepan.jpg", details: "" },
  { id: 88, name: "Ceramic Saucepan", material: "Ceramic", image: "images/Ceramic Saucepan.jpg", details: "" },
  { id: 89, name: "Aluminum Saucepan", material: "Metal", image: "images/Aluminum Saucepan.jpg", details: "" },
  { id: 90, name: "Copper Saucepan", material: "Metal", image: "images/Copper Saucepan.jpg", details: "" },
  { id: 91, name: "Stainless Steel Stockpot", material: "Metal", image: "images/Stainless Steel Stockpot.jpg", details: "" },
  { id: 92, name: "Aluminum Stockpot", material: "Metal", image: "images/Aluminum Stockpot.jpg", details: "" },
  { id: 93, name: "Copper Stockpot", material: "Metal", image: "images/Copper Stockpot.jpg", details: "" },
  { id: 94, name: "Cast Iron Dutch Oven", material: "Metal", image: "images/Cast Iron Dutch Oven.jpg", details: "" },
  { id: 95, name: "Enameled Cast Iron Dutch Oven", material: "Metal", image: "images/Enameled Cast Iron Dutch Oven.jpg", details: "" },
  { id: 96, name: "Ceramic Dutch Oven", material: "Ceramic", image: "images/Ceramic Dutch Oven.jpg", details: "" },
  { id: 97, name: "Metal Roasting Pan (Stainless Steel)", material: "Metal", image: "images/Metal Roasting Pan (Stainless Steel).jpg", details: "" },
  { id: 98, name: "Aluminum Roasting Pan", material: "Metal", image: "images/Aluminum Roasting Pan.jpg", details: "" },
  { id: 99, name: "Nonstick Roasting Pan", material: "Metal", image: "images/Nonstick Roasting Pan.jpg", details: "" },
  { id: 100, name: "Metal Baking Sheet (Aluminum)", material: "Metal", image: "images/Metal Baking Sheet (Aluminum).jpg", details: "" },
  { id: 101, name: "Nonstick Baking Sheet", material: "Metal", image: "images/Nonstick Baking Sheet.jpg", details: "" },
  { id: 103, name: "Metal Oven Tray", material: "Metal", image: "images/Metal Oven Tray.jpg", details: "" },
  { id: 104, name: "Nonstick Oven Tray", material: "Metal", image: "images/Nonstick Oven Tray.jpg", details: "" },
  { id: 106, name: "Ceramic Casserole Dish", material: "Ceramic", image: "images/Ceramic Casserole Dish.jpg", details: "" },
  { id: 107, name: "Glass Casserole Dish", material: "Glass", image: "images/Glass Casserole Dish.jpg", details: "" },
  { id: 108, name: "Metal Casserole Dish", material: "Metal", image: "images/Metal Casserole Dish.jpg", details: "" },
  { id: 109, name: "Stoneware Casserole Dish", material: "Ceramic", image: "images/Stoneware Casserole Dish.jpg", details: "" },
  { id: 110, name: "Metal Pie Pan", material: "Metal", image: "images/Metal Pie Pan.jpg", details: "" },
  { id: 111, name: "Glass Pie Pan", material: "Glass", image: "images/Glass Pie Pan.jpg", details: "" },
  { id: 112, name: "Ceramic Pie Pan", material: "Ceramic", image: "images/Ceramic Pie Pan.jpg", details: "" },
  { id: 113, name: "Aluminum Pie Pan", material: "Metal", image: "images/Aluminum Pie Pan.jpg", details: "" },
  { id: 114, name: "Metal Tart Pan", material: "Metal", image: "images/Metal Tart Pan.jpg", details: "" },
  { id: 115, name: "Nonstick Tart Pan", material: "Metal", image: "images/Nonstick Tart Pan.jpg", details: "" },
  { id: 116, name: "Ceramic Tart Pan", material: "Ceramic", image: "images/Ceramic Tart Pan.jpg", details: "" },
  { id: 117, name: "Metal Muffin Tin", material: "Metal", image: "images/Metal Muffin Tin.jpg", details: "" },
  { id: 118, name: "Silicone Muffin Tin", material: "Plastic", image: "images/Silicone Muffin Tin.jpg", details: "" },
  { id: 119, name: "Nonstick Muffin Tin", material: "Metal", image: "images/Nonstick Muffin Tin.jpg", details: "" },
  { id: 120, name: "Metal Loaf Pan", material: "Metal", image: "images/Metal Loaf Pan.jpg", details: "" },
  { id: 121, name: "Glass Loaf Pan", material: "Glass", image: "images/Glass Loaf Pan.jpg", details: "" },
  { id: 122, name: "Ceramic Loaf Pan", material: "Ceramic", image: "images/Ceramic Loaf Pan.jpg", details: "" },
  { id: 123, name: "Nonstick Loaf Pan", material: "Metal", image: "images/Nonstick Loaf Pan.jpg", details: "" },
  { id: 124, name: "Metal Cookie Sheet (Aluminum)", material: "Metal", image: "images/Metal Cookie Sheet (Aluminum).jpg", details: "" },
  { id: 125, name: "Nonstick Cookie Sheet", material: "Metal", image: "images/Nonstick Cookie Sheet.jpg", details: "" },
  { id: 126, name: "Silicone Cookie Sheet", material: "Plastic", image: "images/Silicone Cookie Sheet.jpg", details: "" },
  { id: 127, name: "Stainless Steel Cooling Rack", material: "Metal", image: "images/Stainless Steel Cooling Rack.jpg", details: "" },
  { id: 128, name: "Plastic Cooling Rack", material: "Plastic", image: "images/Plastic Cooling Rack.jpg", details: "" },
  { id: 129, name: "Cast Iron Griddle", material: "Metal", image: "images/Cast Iron Griddle.jpg", details: "" },
  { id: 130, name: "Nonstick Griddle", material: "Metal", image: "images/Nonstick Griddle.jpg", details: "" },
  { id: 131, name: "Aluminum Griddle", material: "Metal", image: "images/Aluminum Griddle.jpg", details: "" },
  { id: 132, name: "Stainless Steel Pressure Cooker", material: "Metal", image: "images/Stainless Steel Pressure Cooker.jpg", details: "" },
  { id: 133, name: "Aluminum Pressure Cooker", material: "Metal", image: "images/Aluminum Pressure Cooker.jpg", details: "" },
  { id: 134, name: "Slow Cooker", material: "Metal", image: "images/Slow Cooker.jpg", details: "" },
  { id: 135, name: "Rice Cooker", material: "Metal", image: "images/Rice Cooker.jpg", details: "" },
  { id: 136, name: "Carbon Steel Wok", material: "Metal", image: "images/Carbon Steel Wok.jpg", details: "" },
  { id: 137, name: "Cast Iron Wok", material: "Metal", image: "images/Cast Iron Wok.jpg", details: "" },
  { id: 138, name: "Nonstick Wok", material: "Metal", image: "images/Nonstick Wok.jpg", details: "" },
  { id: 139, name: "Stainless Steel Wok", material: "Metal", image: "images/Stainless Steel Wok.jpg", details: "" },
  { id: 140, name: "Stainless Steel Steamer Basket", material: "Metal", image: "images/Stainless Steel Steamer Basket.jpg", details: "" },
  { id: 141, name: "Bamboo Steamer Basket", material: "Wood", image: "images/Bamboo Steamer Basket.jpg", details: "" },
  { id: 142, name: "Silicone Steamer Basket", material: "Plastic", image: "images/Silicone Steamer Basket.jpg", details: "" },
  { id: 143, name: "Metal Colander", material: "Metal", image: "images/Metal Colander.jpg", details: "" },
  { id: 144, name: "Plastic Colander", material: "Plastic", image: "images/Plastic Colander.jpg", details: "" },
  { id: 145, name: "Silicone Colander", material: "Plastic", image: "images/Silicone Colander.jpg", details: "" },
  { id: 146, name: "Ceramic Colander", material: "Ceramic", image: "images/Ceramic Colander.jpg", details: "" },
  { id: 147, name: "Bamboo Colander", material: "Wood", image: "images/Bamboo Colander.jpg", details: "" },
  { id: 148, name: "Metal Strainer (Fine Mesh)", material: "Metal", image: "images/Metal Strainer (Fine Mesh).jpg", details: "" },
  { id: 149, name: "Plastic Strainer", material: "Plastic", image: "images/Plastic Strainer.jpg", details: "" },
  { id: 150, name: "Silicone Strainer", material: "Plastic", image: "images/Silicone Strainer.jpg", details: "" },
  { id: 151, name: "Ceramic Strainer", material: "Ceramic", image: "images/Ceramic Strainer.jpg", details: "" },
  { id: 152, name: "Metal Sieve", material: "Metal", image: "images/Metal Sieve.jpg", details: "" },
  { id: 153, name: "Plastic Sieve", material: "Plastic", image: "images/Plastic Sieve.jpg", details: "" },
  { id: 154, name: "Silicone Sieve", material: "Plastic", image: "images/Silicone Sieve.jpg", details: "" },
  { id: 155, name: "Wooden Sieve", material: "Wood", image: "images/Wooden Sieve.jpg", details: "" },
  { id: 156, name: "Metal Mixing Bowl", material: "Metal", image: "images/Metal Mixing Bowl.jpg", details: "" },
  { id: 157, name: "Glass Mixing Bowl", material: "Glass", image: "images/Glass Mixing Bowl.jpg", details: "" },
  { id: 158, name: "Ceramic Mixing Bowl", material: "Ceramic", image: "images/Ceramic Mixing Bowl.jpg", details: "" },
  { id: 159, name: "Plastic Mixing Bowl", material: "Plastic", image: "images/Plastic Mixing Bowl.jpg", details: "" },
  { id: 160, name: "Wooden Mixing Bowl", material: "Wood", image: "images/Wooden Mixing Bowl.jpg", details: "" },
  { id: 161, name: "Metal Measuring Cup", material: "Metal", image: "images/Metal Measuring Cup.jpg", details: "" },
  { id: 162, name: "Glass Measuring Cup", material: "Glass", image: "images/Glass Measuring Cup.jpg", details: "" },
  { id: 163, name: "Plastic Measuring Cup", material: "Plastic", image: "images/Plastic Measuring Cup.jpg", details: "" },
  { id: 164, name: "Ceramic Measuring Cup", material: "Ceramic", image: "images/Ceramic Measuring Cup.jpg", details: "" },
  { id: 165, name: "Stainless Steel Measuring Cup", material: "Metal", image: "images/Stainless Steel Measuring Cup.jpg", details: "" },
  { id: 166, name: "Metal Measuring Spoon", material: "Metal", image: "images/Metal Measuring Spoon.jpg", details: "" },
  { id: 167, name: "Plastic Measuring Spoon", material: "Plastic", image: "images/Plastic Measuring Spoon.jpg", details: "" },
  { id: 168, name: "Silicone Measuring Spoon", material: "Plastic", image: "images/Silicone Measuring Spoon.jpg", details: "" },
  { id: 169, name: "Stainless Steel Measuring Spoon", material: "Metal", image: "images/Stainless Steel Measuring Spoon.jpg", details: "" },
  { id: 170, name: "Blender", material: "Metal", image: "images/Blender.jpg", details: "" },
  { id: 171, name: "Food Processor", material: "Metal", image: "images/Food Processor.jpg", details: "" },
  { id: 172, name: "Juicer", material: "Metal", image: "images/Juicer.jpg", details: "" },
  { id: 173, name: "Stone Mortar and Pestle", material: "Ceramic", image: "images/Stone Mortar and Pestle.jpg", details: "" },
  { id: 174, name: "Ceramic Mortar and Pestle", material: "Ceramic", image: "images/Ceramic Mortar and Pestle.jpg", details: "" },
  { id: 175, name: "Granite Mortar and Pestle", material: "Ceramic", image: "images/Granite Mortar and Pestle.jpg", details: "" },
  { id: 176, name: "Wooden Mortar and Pestle", material: "Wood", image: "images/Wooden Mortar and Pestle.jpg", details: "" },
  { id: 177, name: "Metal Mortar and Pestle", material: "Metal", image: "images/Metal Mortar and Pestle.jpg", details: "" },
  { id: 178, name: "Wood Cutting Board", material: "Wood", image: "images/Wood Cutting Board.jpg", details: "" },
  { id: 179, name: "Plastic Cutting Board", material: "Plastic", image: "images/Plastic Cutting Board.jpg", details: "" },
  { id: 180, name: "Bamboo Cutting Board", material: "Wood", image: "images/Bamboo Cutting Board.jpg", details: "" },
  { id: 181, name: "Glass Cutting Board", material: "Glass", image: "images/Glass Cutting Board.jpg", details: "" },
  { id: 182, name: "Marble Cutting Board", material: "Ceramic", image: "images/Marble Cutting Board.jpg", details: "" },
  { id: 183, name: "Composite Cutting Board", material: "Plastic", image: "images/Composite Cutting Board.jpg", details: "" },
  { id: 184, name: "Wood Knife Block", material: "Wood", image: "images/Wood Knife Block.jpg", details: "" },
  { id: 185, name: "Plastic Knife Block", material: "Plastic", image: "images/Plastic Knife Block.jpg", details: "" },
  { id: 186, name: "Metal Knife Block", material: "Metal", image: "images/Metal Knife Block.jpg", details: "" },
  { id: 187, name: "Metal Can Opener", material: "Metal", image: "images/Metal Can Opener.jpg", details: "" },
  { id: 188, name: "Plastic Can Opener", material: "Plastic", image: "images/Plastic Can Opener.jpg", details: "" },
  { id: 189, name: "Metal Bottle Opener", material: "Metal", image: "images/Metal Bottle Opener.jpg", details: "" },
  { id: 190, name: "Wooden Bottle Opener", material: "Wood", image: "images/Wooden Bottle Opener.jpg", details: "" },
  { id: 191, name: "Plastic Bottle Opener", material: "Plastic", image: "images/Plastic Bottle Opener.jpg", details: "" },
  { id: 192, name: "Metal Corkscrew", material: "Metal", image: "images/Metal Corkscrew.jpg", details: "" },
  { id: 193, name: "Wooden Corkscrew", material: "Wood", image: "images/Wooden Corkscrew.jpg", details: "" },
  { id: 194, name: "Plastic Corkscrew", material: "Plastic", image: "images/Plastic Corkscrew.jpg", details: "" },
  { id: 195, name: "Plastic Ice Cube Tray", material: "Plastic", image: "images/Plastic Ice Cube Tray.jpg", details: "" },
  { id: 196, name: "Silicone Ice Cube Tray", material: "Plastic", image: "images/Silicone Ice Cube Tray.jpg", details: "" },
  { id: 197, name: "Metal Ice Cube Tray", material: "Metal", image: "images/Metal Ice Cube Tray.jpg", details: "" },
  { id: 198, name: "Glass Ice Cube Tray", material: "Glass", image: "images/Glass Ice Cube Tray.jpg", details: "" },
  { id: 199, name: "Metal Pie Dish", material: "Metal", image: "images/Metal Pie Dish.jpg", details: "" },
  { id: 200, name: "Glass Pie Dish", material: "Glass", image: "images/Glass Pie Dish.jpg", details: "" },
  { id: 201, name: "Ceramic Pie Dish", material: "Ceramic", image: "images/Ceramic Pie Dish.jpg", details: "" },
  { id: 202, name: "Plastic Pie Dish", material: "Plastic", image: "images/Plastic Pie Dish.jpg", details: "" },
  { id: 203, name: "Silicone Pastry Brush", material: "Plastic", image: "images/Silicone Pastry Brush.jpg", details: "" },
  { id: 204, name: "Natural Bristle Pastry Brush", material: "Wood", image: "images/Natural Bristle Pastry Brush.jpg", details: "" },
  { id: 205, name: "Wood Rolling Pin", material: "Wood", image: "images/Wood Rolling Pin.jpg", details: "" },
  { id: 206, name: "Marble Rolling Pin", material: "Ceramic", image: "images/Marble Rolling Pin.jpg", details: "" },
  { id: 207, name: "Stainless Steel Rolling Pin", material: "Metal", image: "images/Stainless Steel Rolling Pin.jpg", details: "" },
  { id: 208, name: "Glass Rolling Pin", material: "Glass", image: "images/Glass Rolling Pin.jpg", details: "" },
  { id: 209, name: "Metal Pastry Cutter", material: "Metal", image: "images/Metal Pastry Cutter.jpg", details: "" },
  { id: 210, name: "Plastic Pastry Cutter", material: "Plastic", image: "images/Plastic Pastry Cutter.jpg", details: "" },
  { id: 211, name: "Stainless Steel Pastry Cutter", material: "Metal", image: "images/Stainless Steel Pastry Cutter.jpg", details: "" },
  { id: 212, name: "Metal Grater", material: "Metal", image: "images/Metal Grater.jpg", details: "" },
  { id: 213, name: "Plastic Grater", material: "Plastic", image: "images/Plastic Grater.jpg", details: "" },
  { id: 214, name: "Ceramic Grater", material: "Ceramic", image: "images/Ceramic Grater.jpg", details: "" },
  { id: 215, name: "Metal Zester", material: "Metal", image: "images/Metal Zester.jpg", details: "" },
  { id: 216, name: "Plastic Zester", material: "Plastic", image: "images/Plastic Zester.jpg", details: "" },
  { id: 217, name: "Metal Mandoline Slicer", material: "Metal", image: "images/Metal Mandoline Slicer.jpg", details: "" },
  { id: 218, name: "Plastic Mandoline Slicer", material: "Plastic", image: "images/Plastic Mandoline Slicer.jpg", details: "" },
  { id: 219, name: "Metal Food Chopper", material: "Metal", image: "images/Metal Food Chopper.jpg", details: "" },
  { id: 220, name: "Plastic Food Chopper", material: "Plastic", image: "images/Plastic Food Chopper.jpg", details: "" },
  { id: 221, name: "Metal Food Mill", material: "Metal", image: "images/Metal Food Mill.jpg", details: "" },
  { id: 222, name: "Plastic Food Mill", material: "Plastic", image: "images/Plastic Food Mill.jpg", details: "" },
  { id: 223, name: "Plastic Salad Spinner", material: "Plastic", image: "images/Plastic Salad Spinner.jpg", details: "" },
  { id: 224, name: "Metal Salad Spinner", material: "Metal", image: "images/Metal Salad Spinner.jpg", details: "" },
  { id: 225, name: "Metal Vegetable Peeler", material: "Metal", image: "images/Metal Vegetable Peeler.jpg", details: "" },
  { id: 226, name: "Plastic Vegetable Peeler", material: "Plastic", image: "images/Plastic Vegetable Peeler.jpg", details: "" },
  { id: 227, name: "Metal Manual Egg Beater", material: "Metal", image: "images/Metal Manual Egg Beater.jpg", details: "" },
  { id: 228, name: "Plastic Manual Egg Beater", material: "Plastic", image: "images/Plastic Manual Egg Beater.jpg", details: "" },
  { id: 229, name: "Metal Whisk", material: "Metal", image: "images/Metal Whisk.jpg", details: "" },
  { id: 230, name: "Silicone Whisk", material: "Plastic", image: "images/Silicone Whisk.jpg", details: "" },
  { id: 231, name: "Wooden Whisk", material: "Wood", image: "images/Wooden Whisk.jpg", details: "" },
  { id: 232, name: "Metal Mixing Spatula", material: "Metal", image: "images/Metal Mixing Spatula.jpg", details: "" },
  { id: 233, name: "Plastic Mixing Spatula", material: "Plastic", image: "images/Plastic Mixing Spatula.jpg", details: "" },
  { id: 234, name: "Silicone Mixing Spatula", material: "Plastic", image: "images/Silicone Mixing Spatula.jpg", details: "" },
  { id: 235, name: "Wooden Mixing Spatula", material: "Wood", image: "images/Wooden Mixing Spatula.jpg", details: "" },
  { id: 236, name: "Metal Soup Ladle", material: "Metal", image: "images/Metal Soup Ladle.jpg", details: "" },
  { id: 237, name: "Plastic Soup Ladle", material: "Plastic", image: "images/Plastic Soup Ladle.jpg", details: "" },
  { id: 238, name: "Wooden Soup Ladle", material: "Wood", image: "images/Wooden Soup Ladle.jpg", details: "" },
  { id: 239, name: "Ceramic Soup Ladle", material: "Ceramic", image: "images/Ceramic Soup Ladle.jpg", details: "" },
  { id: 240, name: "Glass Cream Pitcher", material: "Glass", image: "images/Glass Cream Pitcher.jpg", details: "" },
  { id: 241, name: "Ceramic Cream Pitcher", material: "Ceramic", image: "images/Ceramic Cream Pitcher.jpg", details: "" },
  { id: 242, name: "Plastic Cream Pitcher", material: "Plastic", image: "images/Plastic Cream Pitcher.jpg", details: "" },
  { id: 243, name: "Metal Cream Pitcher", material: "Metal", image: "images/Metal Cream Pitcher.jpg", details: "" },
  { id: 244, name: "Glass Butter Dish", material: "Glass", image: "images/Glass Butter Dish.jpg", details: "" },
  { id: 245, name: "Ceramic Butter Dish", material: "Ceramic", image: "images/Ceramic Butter Dish.jpg", details: "" },
  { id: 246, name: "Plastic Butter Dish", material: "Plastic", image: "images/Plastic Butter Dish.jpg", details: "" },
  { id: 247, name: "Metal Butter Dish", material: "Metal", image: "images/Metal Butter Dish.jpg", details: "" },
  { id: 248, name: "Metal Cheese Grater", material: "Metal", image: "images/Metal Cheese Grater.jpg", details: "" },
  { id: 249, name: "Plastic Cheese Grater", material: "Plastic", image: "images/Plastic Cheese Grater.jpg", details: "" },
  { id: 250, name: "Ceramic Fondue Pot", material: "Ceramic", image: "images/Ceramic Fondue Pot.jpg", details: "" },
  { id: 251, name: "Metal Fondue Pot", material: "Metal", image: "images/Metal Fondue Pot.jpg", details: "" },
  { id: 252, name: "Cast Iron Fondue Pot", material: "Metal", image: "images/Cast Iron Fondue Pot.jpg", details: "" },
  { id: 253, name: "Metal Fondue Fork", material: "Metal", image: "images/Metal Fondue Fork.jpg", details: "" },
  { id: 254, name: "Wooden Fondue Fork", material: "Wood", image: "images/Wooden Fondue Fork.jpg", details: "" },
  { id: 255, name: "Bamboo Sushi Rolling Mat", material: "Wood", image: "images/Bamboo Sushi Rolling Mat.jpg", details: "" },
  { id: 256, name: "Plastic Sushi Rolling Mat", material: "Plastic", image: "images/Plastic Sushi Rolling Mat.jpg", details: "" },
  { id: 257, name: "Plastic Bento Box", material: "Plastic", image: "images/Plastic Bento Box.jpg", details: "" },
  { id: 258, name: "Metal Bento Box", material: "Metal", image: "images/Metal Bento Box.jpg", details: "" },
  { id: 259, name: "Wooden Bento Box", material: "Wood", image: "images/Wooden Bento Box.jpg", details: "" },
  { id: 260, name: "Ceramic Bento Box", material: "Ceramic", image: "images/Ceramic Bento Box.jpg", details: "" },
  { id: 261, name: "Plastic Tupperware Container", material: "Plastic", image: "images/Plastic Tupperware Container.jpg", details: "" },
  { id: 262, name: "Glass Food Storage Container", material: "Glass", image: "images/Glass Food Storage Container.jpg", details: "" },
  { id: 263, name: "Stainless Steel Food Storage Container", material: "Metal", image: "images/Stainless Steel Food Storage Container.jpg", details: "" },
  { id: 264, name: "Glass Salad Bowl", material: "Glass", image: "images/Glass Salad Bowl.jpg", details: "" },
  { id: 265, name: "Ceramic Salad Bowl", material: "Ceramic", image: "images/Ceramic Salad Bowl.jpg", details: "" },
  { id: 266, name: "Metal Salad Bowl", material: "Metal", image: "images/Metal Salad Bowl.jpg", details: "" },
  { id: 267, name: "Wooden Salad Bowl", material: "Wood", image: "images/Wooden Salad Bowl.jpg", details: "" },
  { id: 268, name: "Plastic Salad Bowl", material: "Plastic", image: "images/Plastic Salad Bowl.jpg", details: "" },
  { id: 269, name: "Metal Serving Tray", material: "Metal", image: "images/Metal Serving Tray.jpg", details: "" },
  { id: 270, name: "Wooden Serving Tray", material: "Wood", image: "images/Wooden Serving Tray.jpg", details: "" },
  { id: 271, name: "Plastic Serving Tray", material: "Plastic", image: "images/Plastic Serving Tray.jpg", details: "" },
  { id: 272, name: "Glass Serving Tray", material: "Glass", image: "images/Glass Serving Tray.jpg", details: "" },
  { id: 273, name: "Ceramic Serving Tray", material: "Ceramic", image: "images/Ceramic Serving Tray.jpg", details: "" },
  { id: 274, name: "Metal Serving Spoon", material: "Metal", image: "images/Metal Serving Spoon.jpg", details: "" },
  { id: 275, name: "Wooden Serving Spoon", material: "Wood", image: "images/Wooden Serving Spoon.jpg", details: "" },
  { id: 276, name: "Plastic Serving Spoon", material: "Plastic", image: "images/Plastic Serving Spoon.jpg", details: "" },
  { id: 277, name: "Ceramic Serving Spoon", material: "Ceramic", image: "images/Ceramic Serving Spoon.jpg", details: "" },
  { id: 278, name: "Metal Serving Fork", material: "Metal", image: "images/Metal Serving Fork.jpg", details: "" },
  { id: 279, name: "Wooden Serving Fork", material: "Wood", image: "images/Wooden Serving Fork.jpg", details: "" },
  { id: 280, name: "Plastic Serving Fork", material: "Plastic", image: "images/Plastic Serving Fork.jpg", details: "" },
  { id: 281, name: "Ceramic Serving Fork", material: "Ceramic", image: "images/Ceramic Serving Fork.jpg", details: "" },
  { id: 282, name: "Ceramic Soup Bowl", material: "Ceramic", image: "images/Ceramic Soup Bowl.jpg", details: "" },
  { id: 283, name: "Glass Soup Bowl", material: "Glass", image: "images/Glass Soup Bowl.jpg", details: "" },
  { id: 284, name: "Metal Soup Bowl", material: "Metal", image: "images/Metal Soup Bowl.jpg", details: "" },
  { id: 285, name: "Wooden Soup Bowl", material: "Wood", image: "images/Wooden Soup Bowl.jpg", details: "" },
  { id: 286, name: "Plastic Soup Bowl", material: "Plastic", image: "images/Plastic Soup Bowl.jpg", details: "" },
  { id: 287, name: "Ceramic Dessert Plate", material: "Ceramic", image: "images/Ceramic Dessert Plate.jpg", details: "" },
  { id: 288, name: "Glass Dessert Plate", material: "Glass", image: "images/Glass Dessert Plate.jpg", details: "" },
  { id: 289, name: "Metal Dessert Plate", material: "Metal", image: "images/Metal Dessert Plate.jpg", details: "" },
  { id: 290, name: "Plastic Dessert Plate", material: "Plastic", image: "images/Plastic Dessert Plate.jpg", details: "" },
  { id: 291, name: "Wooden Dessert Plate", material: "Wood", image: "images/Wooden Dessert Plate.jpg", details: "" },
  { id: 292, name: "Ceramic Snack Bowl", material: "Ceramic", image: "images/Ceramic Snack Bowl.jpg", details: "" },
  { id: 293, name: "Glass Snack Bowl", material: "Glass", image: "images/Glass Snack Bowl.jpg", details: "" },
  { id: 294, name: "Metal Snack Bowl", material: "Metal", image: "images/Metal Snack Bowl.jpg", details: "" },
  { id: 295, name: "Plastic Snack Bowl", material: "Plastic", image: "images/Plastic Snack Bowl.jpg", details: "" },
  { id: 296, name: "Wooden Snack Bowl", material: "Wood", image: "images/Wooden Snack Bowl.jpg", details: "" },
  { id: 297, name: "Metal Water Bottle (Stainless Steel)", material: "Metal", image: "images/Metal Water Bottle (Stainless Steel).jpg", details: "" },
  { id: 298, name: "Plastic Water Bottle", material: "Plastic", image: "images/Plastic Water Bottle.jpg", details: "" },
  { id: 299, name: "Glass Water Bottle", material: "Glass", image: "images/Glass Water Bottle.jpg", details: "" },
  { id: 300, name: "Aluminum Water Bottle", material: "Metal", image: "images/Aluminum Water Bottle.jpg", details: "" },
  { id: 301, name: "Stainless Steel Thermos", material: "Metal", image: "images/Stainless Steel Thermos.jpg", details: "" },
  { id: 302, name: "Plastic Thermos", material: "Plastic", image: "images/Plastic Thermos.jpg", details: "" },
  { id: 303, name: "Glass Milk Jug", material: "Glass", image: "images/Glass Milk Jug.jpg", details: "" },
  { id: 304, name: "Plastic Milk Jug", material: "Plastic", image: "images/Plastic Milk Jug.jpg", details: "" },
  { id: 305, name: "Ceramic Milk Jug", material: "Ceramic", image: "images/Ceramic Milk Jug.jpg", details: "" },
  { id: 306, name: "Glass Pitcher", material: "Glass", image: "images/Glass Pitcher.jpg", details: "" },
  { id: 307, name: "Ceramic Pitcher", material: "Ceramic", image: "images/Ceramic Pitcher.jpg", details: "" },
  { id: 308, name: "Plastic Pitcher", material: "Plastic", image: "images/Plastic Pitcher.jpg", details: "" },
  { id: 309, name: "Metal Pitcher", material: "Metal", image: "images/Metal Pitcher.jpg", details: "" },
  { id: 310, name: "Metal Ice Bucket", material: "Metal", image: "images/Metal Ice Bucket.jpg", details: "" },
  { id: 311, name: "Plastic Ice Bucket", material: "Plastic", image: "images/Plastic Ice Bucket.jpg", details: "" },
  { id: 312, name: "Glass Ice Bucket", material: "Glass", image: "images/Glass Ice Bucket.jpg", details: "" },
  { id: 313, name: "Glass Beverage Dispenser", material: "Glass", image: "images/Glass Beverage Dispenser.jpg", details: "" },
  { id: 314, name: "Plastic Beverage Dispenser", material: "Plastic", image: "images/Plastic Beverage Dispenser.jpg", details: "" },
  { id: 315, name: "Metal Beverage Dispenser", material: "Metal", image: "images/Metal Beverage Dispenser.jpg", details: "" },
  { id: 316, name: "Plastic Food Storage Container", material: "Plastic", image: "images/Plastic Food Storage Container.jpg", details: "" },
  { id: 317, name: "Glass Food Storage Container", material: "Glass", image: "images/Glass Food Storage Container.jpg", details: "" },
  { id: 318, name: "Stainless Steel Food Storage Container", material: "Metal", image: "images/Stainless Steel Food Storage Container.jpg", details: "" },
  { id: 319, name: "Ceramic Food Storage Container", material: "Ceramic", image: "images/Ceramic Food Storage Container.jpg", details: "" },
  { id: 320, name: "Metal Pizza Cutter", material: "Metal", image: "images/Metal Pizza Cutter.jpg", details: "" },
  { id: 321, name: "Plastic Pizza Cutter", material: "Plastic", image: "images/Plastic Pizza Cutter.jpg", details: "" },
  { id: 322, name: "Metal Salad Tongs", material: "Metal", image: "images/Metal Salad Tongs.jpg", details: "" },
  { id: 323, name: "Plastic Salad Tongs", material: "Plastic", image: "images/Plastic Salad Tongs.jpg", details: "" },
  { id: 324, name: "Wooden Salad Tongs", material: "Wood", image: "images/Wooden Salad Tongs.jpg", details: "" },
  { id: 325, name: "Fabric Pot Holder (Cotton)", material: "Fabric", image: "images/Fabric Pot Holder (Cotton).jpg", details: "" },
  { id: 326, name: "Silicone Pot Holder", material: "Plastic", image: "images/Silicone Pot Holder.jpg", details: "" },
  { id: 327, name: "Fabric Oven Mitt", material: "Fabric", image: "images/Fabric Oven Mitt.jpg", details: "" },
  { id: 328, name: "Silicone Oven Mitt", material: "Plastic", image: "images/Silicone Oven Mitt.jpg", details: "" },
  { id: 329, name: "Metal Spice Grinder", material: "Metal", image: "images/Metal Spice Grinder.jpg", details: "" },
  { id: 330, name: "Plastic Spice Grinder", material: "Plastic", image: "images/Plastic Spice Grinder.jpg", details: "" },
  { id: 331, name: "Ceramic Spice Grinder", material: "Ceramic", image: "images/Ceramic Spice Grinder.jpg", details: "" },
  { id: 332, name: "Metal Herb Stripper", material: "Metal", image: "images/Metal Herb Stripper.jpg", details: "" },
  { id: 333, name: "Plastic Herb Stripper", material: "Plastic", image: "images/Plastic Herb Stripper.jpg", details: "" },
  { id: 334, name: "Metal Egg Separator", material: "Metal", image: "images/Metal Egg Separator.jpg", details: "" },
  { id: 335, name: "Plastic Egg Separator", material: "Plastic", image: "images/Plastic Egg Separator.jpg", details: "" },
  { id: 336, name: "Metal Cooking Thermometer", material: "Metal", image: "images/Metal Cooking Thermometer.jpg", details: "" },
  { id: 337, name: "Plastic Cooking Thermometer", material: "Plastic", image: "images/Plastic Cooking Thermometer.jpg", details: "" },
  { id: 338, name: "Digital Cooking Thermometer", material: "Metal", image: "images/Digital Cooking Thermometer.jpg", details: "" },
  { id: 339, name: "Stainless Steel Cooking Thermometer", material: "Metal", image: "images/Stainless Steel Cooking Thermometer.jpg", details: "" },
  { id: 340, name: "Digital Food Scale", material: "Metal", image: "images/Digital Food Scale.jpg", details: "" },
  { id: 341, name: "Mechanical Food Scale", material: "Metal", image: "images/Mechanical Food Scale.jpg", details: "" },
  { id: 342, name: "Metal Pressure Canner", material: "Metal", image: "images/Metal Pressure Canner.jpg", details: "" },
  { id: 343, name: "Aluminum Pressure Canner", material: "Metal", image: "images/Aluminum Pressure Canner.jpg", details: "" },
  { id: 344, name: "Metal Food Steamer", material: "Metal", image: "images/Metal Food Steamer.jpg", details: "" },
  { id: 345, name: "Plastic Food Steamer", material: "Plastic", image: "images/Plastic Food Steamer.jpg", details: "" },
  { id: 346, name: "Stainless Steel Food Steamer", material: "Metal", image: "images/Stainless Steel Food Steamer.jpg", details: "" },
  { id: 347, name: "Metal Butter Cutter", material: "Metal", image: "images/Metal Butter Cutter.jpg", details: "" },
  { id: 348, name: "Plastic Butter Cutter", material: "Plastic", image: "images/Plastic Butter Cutter.jpg", details: "" },
  { id: 349, name: "Metal Meat Tenderizer", material: "Metal", image: "images/Metal Meat Tenderizer.jpg", details: "" },
  { id: 350, name: "Wooden Meat Tenderizer", material: "Wood", image: "images/Wooden Meat Tenderizer.jpg", details: "" },
  { id: 351, name: "Plastic Meat Tenderizer", material: "Plastic", image: "images/Plastic Meat Tenderizer.jpg", details: "" },
  { id: 352, name: "Metal Grill Tongs", material: "Metal", image: "images/Metal Grill Tongs.jpg", details: "" },
  { id: 353, name: "Wooden Grill Tongs", material: "Wood", image: "images/Wooden Grill Tongs.jpg", details: "" },
  { id: 354, name: "Plastic Grill Tongs", material: "Plastic", image: "images/Plastic Grill Tongs.jpg", details: "" },
  { id: 355, name: "Metal Skewer", material: "Metal", image: "images/Metal Skewer.jpg", details: "" },
  { id: 356, name: "Bamboo Skewer", material: "Wood", image: "images/Bamboo Skewer.jpg", details: "" },
  { id: 357, name: "Wooden Skewer", material: "Wood", image: "images/Wooden Skewer.jpg", details: "" },
  { id: 358, name: "Stainless Steel Skewer", material: "Metal", image: "images/Stainless Steel Skewer.jpg", details: "" },
  { id: 359, name: "Metal Barbecue Fork", material: "Metal", image: "images/Metal Barbecue Fork.jpg", details: "" },
  { id: 360, name: "Wooden Barbecue Fork", material: "Wood", image: "images/Wooden Barbecue Fork.jpg", details: "" },
  { id: 361, name: "Plastic Barbecue Fork", material: "Plastic", image: "images/Plastic Barbecue Fork.jpg", details: "" },
  { id: 362, name: "Plastic Fondant Smoother", material: "Plastic", image: "images/Plastic Fondant Smoother.jpg", details: "" },
  { id: 363, name: "Metal Fondant Smoother", material: "Metal", image: "images/Metal Fondant Smoother.jpg", details: "" },
  { id: 364, name: "Metal Crinkle Cutter", material: "Metal", image: "images/Metal Crinkle Cutter.jpg", details: "" },
  { id: 365, name: "Plastic Crinkle Cutter", material: "Plastic", image: "images/Plastic Crinkle Cutter.jpg", details: "" },
  { id: 366, name: "Stainless Steel Crinkle Cutter", material: "Metal", image: "images/Stainless Steel Crinkle Cutter.jpg", details: "" },
  { id: 367, name: "Plastic Dough Docker", material: "Plastic", image: "images/Plastic Dough Docker.jpg", details: "" },
  { id: 368, name: "Metal Dough Docker", material: "Metal", image: "images/Metal Dough Docker.jpg", details: "" },
  { id: 369, name: "Metal Pastry Wheel", material: "Metal", image: "images/Metal Pastry Wheel.jpg", details: "" },
  { id: 370, name: "Plastic Pastry Wheel", material: "Plastic", image: "images/Plastic Pastry Wheel.jpg", details: "" },
  { id: 371, name: "Metal Egg Poacher", material: "Metal", image: "images/Metal Egg Poacher.jpg", details: "" },
  { id: 372, name: "Silicone Egg Poacher", material: "Plastic", image: "images/Silicone Egg Poacher.jpg", details: "" },
  { id: 373, name: "Ceramic Egg Poacher", material: "Ceramic", image: "images/Ceramic Egg Poacher.jpg", details: "" },
  { id: 374, name: "Metal Splatter Screen", material: "Metal", image: "images/Metal Splatter Screen.jpg", details: "" },
  { id: 375, name: "Silicone Splatter Screen", material: "Plastic", image: "images/Silicone Splatter Screen.jpg", details: "" },
  { id: 376, name: "Plastic Splatter Screen", material: "Plastic", image: "images/Plastic Splatter Screen.jpg", details: "" },
  { id: 377, name: "Silicone Baking Mat", material: "Plastic", image: "images/Silicone Baking Mat.jpg", details: "" },
  { id: 378, name: "Metal Coffee Grinder", material: "Metal", image: "images/Metal Coffee Grinder.jpg", details: "" },
  { id: 379, name: "Plastic Coffee Grinder", material: "Plastic", image: "images/Plastic Coffee Grinder.jpg", details: "" },
  { id: 380, name: "Metal Popcorn Maker", material: "Metal", image: "images/Metal Popcorn Maker.jpg", details: "" },
  { id: 381, name: "Plastic Popcorn Maker", material: "Plastic", image: "images/Plastic Popcorn Maker.jpg", details: "" },
  { id: 382, name: "Panini Press", material: "Metal", image: "images/Panini Press.jpg", details: "" },
  { id: 383, name: "Electric Griddle", material: "Metal", image: "images/Electric Griddle.jpg", details: "" },
  { id: 384, name: "Sous Vide Machine", material: "Metal", image: "images/Sous Vide Machine.jpg", details: "" },
  { id: 385, name: "Vacuum Sealer", material: "Metal", image: "images/Vacuum Sealer.jpg", details: "" },
  { id: 386, name: "Metal Salad Dressing Mixer", material: "Metal", image: "images/Metal Salad Dressing Mixer.jpg", details: "" },
  { id: 387, name: "Plastic Salad Dressing Mixer", material: "Plastic", image: "images/Plastic Salad Dressing Mixer.jpg", details: "" },
  { id: 388, name: "Metal Candy Thermometer", material: "Metal", image: "images/Metal Candy Thermometer.jpg", details: "" },
  { id: 389, name: "Plastic Candy Thermometer", material: "Plastic", image: "images/Plastic Candy Thermometer.jpg", details: "" },
  { id: 390, name: "Digital Candy Thermometer", material: "Metal", image: "images/Digital Candy Thermometer.jpg", details: "" },
  { id: 391, name: "Ice Cream Maker", material: "Metal", image: "images/Ice Cream Maker.jpg", details: "" }
];
